# group_vars/all.yml
# Variables available to ALL servers and ALL roles
---
patch_author: 'admin'
notify_email: 'ops@company.com'
reboot_timeout: 300
take_snapshot: false

# Toggle this to 'false' to apply ALL available updates, not just security ones
apply_security_only: true

critical_services:
  - sshd
  - chronyd
