# hosts.ini - Server Inventory File
# Format: alias ansible_host=IP_ADDRESS

[webservers]                             # Group name
web01 ansible_host=13.49.44.134          # Server 1 - replace with your EC2 IP
web02 ansible_host=13.62.104.42         # Server 2 - replace with your EC2 IP

[dbservers]                              # Another group (empty for now)
# db01 ansible_host=54.123.45.69

[all:vars]                               # Variables for ALL servers
ansible_ssh_private_key_file=~/.ssh/Ansible_test.pem
ansible_user=ec2-user

[webservers:vars]                        # Variables only for webservers group
patch_reboot_required=true               # Reboot after patching
