---
all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/Ansible_test.pem
    
    # We leave ansible_user undefined here, as it can vary per OS (ec2-user, ubuntu, admin, etc.)
    # Define it per group if needed, or rely on the default in ansible.cfg
  
  children:
    webservers:
      vars:
        patch_reboot_required: true
      hosts:
        web01:
          ansible_host: 13.49.44.134
          ansible_user: ec2-user
        web02:
          ansible_host: 13.62.104.42
          ansible_user: ec2-user
          
    dbservers:
      hosts: {} # Add DB servers here